# Generated by Django 5.2.4 on 2025-07-17 07:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_primer_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='fecha_inscripcion',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='profesion',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='fecha_nacimiento',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='especialidad',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='profesor',
            name='fecha_contratacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='curso',
            name='duracion_en_semanas',
            field=models.PositiveIntegerField(),
        ),
    ]
