# Generated by Django 5.2.4 on 2025-07-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_primer_app', '0002_remove_estudiante_fecha_inscripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='curso',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='cursos',
            field=models.ManyToManyField(blank=True, related_name='estudiantes', to='mi_primer_app.curso'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='cursos',
            field=models.ManyToManyField(blank=True, related_name='profesores', to='mi_primer_app.curso'),
        ),
    ]
